export default {
  LOAD_RECIPES: 'LOAD_RECIPES',
  FAILED_LOAD_RECIPES: 'LOAD_RECIPES',
  LOAD_RECIPEID: 'LOAD_RECIPEID',
  FAILED_LOAD_RECIPEID: 'LOAD_RECIPEID',
  LOAD_USERID: 'LOAD_USERID',
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER: 'SET_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  ERROR_GENERAL: 'ERROR_GENERAL'
};
